version: '3.8'
volumes:
  db:
  pg_data:
  conduktor_data:
services:
  mysql:
    image: mysql:8.0.34
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: io_task
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: io_task
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    tmpfs:
      - /ok
    healthcheck:
      test: 'test -f /ok/ok || ( mysql --user=root --password=password --execute "SHOW DATABASES;" && touch /ok/ok )'
      interval: 1s
      timeout: 3s
      retries: 120

  io-task:
    depends_on:
      mysql:
        condition: service_healthy
    image: io-task:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: "mysql"